### ISSUE TITLE
CPPISetOwner Error

### ISSUE THREAD

**Issue by ghost** [n00bmobile/BaseWars#6]
Hello, here's the error:
[ERROR] gamemodes/basewars/gamemode/buymenu.lua:53: attempt to call method 'CPPISetOwner' (a nil value)
  1. func - gamemodes/basewars/gamemode/buymenu.lua:53
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by n00bmobile** [comment]
This gamemode requires a CPPI compliant prop protection addon to run. My recommendation is to use FPP, but ultimately It's up to you.
